import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import type { WorkspaceRecord } from "../types/db.js";

type UserCodexTemplate = {
  modelProvider: string | undefined;
  approvalsReviewer: string | undefined;
  modelContextWindow: string | undefined;
  modelAutoCompactTokenLimit: string | undefined;
  agentsMaxDepth: string | undefined;
  agentsMaxThreads: string | undefined;
  tuiStatusLine: string | undefined;
  featureMultiAgent: string | undefined;
  featureChildAgentsMd: string | undefined;
  featureCodexHooks: string | undefined;
  context7Block: string[] | undefined;
  modelProviderBlock: string[] | undefined;
};

export function syncWorkspaceCodexConfig(workspace: WorkspaceRecord): void {
  const codexDir = path.join(workspace.rootPath, ".codex");
  fs.mkdirSync(codexDir, { recursive: true });
  fs.writeFileSync(
    path.join(codexDir, "config.toml"),
    buildWorkspaceCodexConfigToml(workspace),
    "utf8"
  );
}

function buildWorkspaceCodexConfigToml(workspace: WorkspaceRecord): string {
  const template = readUserCodexTemplate();
  const lines = [
    "# Generated by codex-feishu",
    `model = ${toTomlString(workspace.defaultModel)}`,
    `model_reasoning_effort = ${toTomlString(workspace.defaultEffort)}`
  ];

  if (template.modelProvider) {
    lines.push(`model_provider = ${toTomlString(template.modelProvider)}`);
  }
  if (template.approvalsReviewer) {
    lines.push(`approvals_reviewer = ${toTomlString(template.approvalsReviewer)}`);
  }
  if (template.modelContextWindow) {
    lines.push(`model_context_window = ${template.modelContextWindow}`);
  }
  if (template.modelAutoCompactTokenLimit) {
    lines.push(
      `model_auto_compact_token_limit = ${template.modelAutoCompactTokenLimit}`
    );
  }

  if (template.agentsMaxDepth || template.agentsMaxThreads) {
    lines.push("", "[agents]");
    if (template.agentsMaxDepth) {
      lines.push(`max_depth = ${template.agentsMaxDepth}`);
    }
    if (template.agentsMaxThreads) {
      lines.push(`max_threads = ${template.agentsMaxThreads}`);
    }
  }

  lines.push("", `[projects.${toTomlString(workspace.rootPath)}]`, 'trust_level = "trusted"');

  if (template.tuiStatusLine) {
    lines.push("", "[tui]", `status_line = ${template.tuiStatusLine}`);
  }

  if (
    template.featureMultiAgent ||
    template.featureChildAgentsMd ||
    template.featureCodexHooks
  ) {
    lines.push("", "[features]");
    if (template.featureMultiAgent) {
      lines.push(`multi_agent = ${template.featureMultiAgent}`);
    }
    if (template.featureChildAgentsMd) {
      lines.push(`child_agents_md = ${template.featureChildAgentsMd}`);
    }
    if (template.featureCodexHooks) {
      lines.push(`codex_hooks = ${template.featureCodexHooks}`);
    }
  }

  if (template.context7Block && template.context7Block.length > 0) {
    lines.push("", "[mcp_servers]", "", ...template.context7Block);
  }

  if (template.modelProviderBlock && template.modelProviderBlock.length > 0) {
    lines.push("", ...template.modelProviderBlock);
  }

  return `${lines.join("\n").trim()}\n`;
}

function readUserCodexTemplate(): UserCodexTemplate {
  const configPath = path.join(os.homedir(), ".codex", "config.toml");
  if (!fs.existsSync(configPath)) {
    return withDefaultModelProvider({
      modelProvider: undefined,
      approvalsReviewer: undefined,
      modelContextWindow: undefined,
      modelAutoCompactTokenLimit: undefined,
      agentsMaxDepth: undefined,
      agentsMaxThreads: undefined,
      tuiStatusLine: undefined,
      featureMultiAgent: undefined,
      featureChildAgentsMd: undefined,
      featureCodexHooks: undefined,
      context7Block: undefined,
      modelProviderBlock: undefined
    });
  }

  const raw = fs.readFileSync(configPath, "utf8");
  const inferredModelProvider = inferModelProvider(raw);
  const modelProvider =
    normalizeTomlStringScalar(extractScalar(raw, "model_provider")) ??
    inferredModelProvider;
  return withDefaultModelProvider({
    modelProvider,
    approvalsReviewer: normalizeTomlStringScalar(
      extractScalar(raw, "approvals_reviewer")
    ),
    modelContextWindow: extractScalar(raw, "model_context_window"),
    modelAutoCompactTokenLimit: extractScalar(raw, "model_auto_compact_token_limit"),
    agentsMaxDepth: extractSectionScalar(raw, "agents", "max_depth"),
    agentsMaxThreads: extractSectionScalar(raw, "agents", "max_threads"),
    tuiStatusLine: extractSectionArray(raw, "tui", "status_line"),
    featureMultiAgent: extractSectionScalar(raw, "features", "multi_agent"),
    featureChildAgentsMd: extractSectionScalar(raw, "features", "child_agents_md"),
    featureCodexHooks: extractSectionScalar(raw, "features", "codex_hooks"),
    context7Block: extractNamedBlock(raw, "[mcp_servers.context7]"),
    modelProviderBlock: modelProvider
      ? extractNamedBlock(raw, `[model_providers.${stripTomlString(modelProvider)}]`)
      : undefined
  });
}

function withDefaultModelProvider(template: UserCodexTemplate): UserCodexTemplate {
  if (template.modelProvider) {
    return template;
  }

  return {
    ...template,
    modelProvider: "localproxy",
    modelProviderBlock: [
      "[model_providers.localproxy]",
      'base_url = "http://192.168.0.5:8317/v1"',
      'env_key = "API_DARL"',
      'name = "LocalProxy"'
    ]
  };
}

function inferModelProvider(source: string): string | undefined {
  const blockHeaders = source.match(/^\[model_providers\.([^\]]+)\]$/gm) || [];
  if (blockHeaders.length === 0) {
    return undefined;
  }

  const firstHeader = blockHeaders[0] ?? "";
  const match = firstHeader.match(/^\[model_providers\.([^\]]+)\]$/);
  return match?.[1]?.trim();
}

function extractScalar(source: string, key: string): string | undefined {
  const match = source.match(new RegExp(`^${escapeRegExp(key)}\\s*=\\s*(.+)$`, "m"));
  return match?.[1]?.trim();
}

function extractSectionScalar(
  source: string,
  section: string,
  key: string
): string | undefined {
  const block = extractSectionBody(source, section);
  if (!block) {
    return undefined;
  }
  const match = block.match(new RegExp(`^${escapeRegExp(key)}\\s*=\\s*(.+)$`, "m"));
  return match?.[1]?.trim();
}

function extractSectionArray(
  source: string,
  section: string,
  key: string
): string | undefined {
  return extractSectionScalar(source, section, key);
}

function extractNamedBlock(source: string, header: string): string[] | undefined {
  const lines = source.split("\n");
  const start = lines.findIndex((line) => line.trim() === header);
  if (start < 0) {
    return undefined;
  }

  const block: string[] = [header];
  for (let index = start + 1; index < lines.length; index += 1) {
    const line = lines[index] ?? "";
    if (line.trim().startsWith("[") && line.trim() !== header) {
      break;
    }
    if (!line.trim()) {
      continue;
    }
    block.push(line);
  }
  return block;
}

function extractSectionBody(source: string, section: string): string | undefined {
  const lines = source.split("\n");
  const start = lines.findIndex((line) => line.trim() === `[${section}]`);
  if (start < 0) {
    return undefined;
  }

  const body: string[] = [];
  for (let index = start + 1; index < lines.length; index += 1) {
    const line = lines[index] ?? "";
    if (line.trim().startsWith("[")) {
      break;
    }
    body.push(line);
  }

  return body.join("\n");
}

function toTomlString(value: string): string {
  return JSON.stringify(value);
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function stripTomlString(value: string): string {
  return value.trim().replace(/^['"]|['"]$/g, "");
}

function normalizeTomlStringScalar(value: string | undefined): string | undefined {
  if (!value) {
    return undefined;
  }
  return stripTomlString(value);
}
